### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KeeJef** [m2049r/monerujo-site#23]
Hey Guys

We have used elements of this website in one of our projects, just realized that this repo does not explicitly mention an associated licence. If you could add a licences or just let me know the terms of use in this issue that would be great. 

Thanks!

**Comment by erciccione** [comment]
Hi @KeeJef I just opened a #25. If you used parts of the website in past shouldn't be a problem, since there wasn't any license in place at the time. I'm not a licensing expert by any meaning, so if somebody knows more than me, please comment.
